config/routes.rb
Rails.application.routes.draw do
  
  get 'credit_cards/new'
  post 'credit_cards/create'
  get 'credit_cards/edit'
  post 'credit_cards/update'

  post 'stripe/webhook'

  get 'sales/new' => 'sales#new', as: :guest_checkout
  post 'sales/create' 
  get 'sales/show', as: :purchase_confirmation

  get 'products/show'
  get 'products/download' => 'products#download', as: :download
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'subscriptions/new' => 'subscriptions#new', as: :new_subscription
  post 'subscriptions/create' => 'subscriptions#create'
  
  get 'pricing' => 'welcome#pricing'
    

  root 'welcome#index'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
  
  def update_credit_card_expiration_date(expiration_month, expiration_year)
    self.expiration_month = expiration_month
    self.expiration_year = expiration_year
    self.save!
  end
  
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController  
  include StripeExceptionHandler
  
  layout 'stripe'
  before_action :authenticate_user!
  
  def new
  end
  
  
  def create    
    log_message = 'Add new credit card failed due to'
    user_message = 'Add new credit card failed. We have been notified about this problem.'
    
    run_with_exception_handler(log_message, user_message) do
      @card = Actors::Customer::UseCases.add_new_credit_card(current_user, params[:stripeToken])
    end
  end
  
  # This is used only for changing the expiration date when a customer clicks the link in the email.
  def edit
    @credit_card = current_user.credit_card
  end

  def update
    log_message = 'Credit card update failed due to'
    user_message = 'Credit card update failed. We have been notified about this problem.'
    
    run_with_exception_handler(log_message, user_message) do
      Actors::Customer::UseCases.update_credit_card_expiration_date(current_user, 
                                                                    params[:card_month], 
                                                                    params[:card_year])
      @user = current_user
      flash.notice = 'Credit card update successful'      
    end    
  end
  
end

app/views/credit_cards/create.html.erb
Your credit card ending in last 4 digits <%= @card.last4 %> has been added.

app/views/credit_cards/edit.html.erb
<%= form_for(@credit_card, :url => credit_cards_update_url, :html => {:method => :post}) do |f| %>

      <h3>Change Expiration Date for Credit Card</h3>

	  <div class="form-row">
	    <label>
	      <span>Your Credit Card Last 4 Digits : <%= @credit_card.last4digits %></span>
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>Expiration</span>
	<%= select_month @credit_card.expiration_month, {add_month_numbers: true}, {name: 'card_month', id: "card_month"} %>

	    </label>
	    <span>/</span>
		<%= select_year @credit_card.expiration_year, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: "card_year", id: "card_year"} %>

	  </div>

	  <button type="submit" class='btn btn-primary'>Change Expiration Date</button>

<% end %>

app/views/credit_cards/new.html.erb
<form action="create" method="POST" id="payment-form">
  <span class="payment-errors">
  	<noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </span>
  <% if @error_message %>
	<%= @error_message %>
  <% end %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration</span>
<%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", data: {stripe: "exp-month"}} %>

    </label>
    <span>/</span>
	<%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", data: {stripe: "exp-year"}} %>

  </div>

  <button type="submit" class='btn btn-primary'>Add Credit Card</button>
</form>	

app/views/credit_cards/update.html.erb
<fieldset>
  <legend>Credit Card Update </legend>

Expiration date for your credit card ending in last 4 digits : <%= @user.credit_card.last4digits %>
has been updated to : <%= @user.credit_card.expiration_month %> / <%= @user.credit_card.expiration_year %>
	
</fieldset>