config/routes.rb
Rails.application.routes.draw do
  
  get 'credit_cards/new'
  post 'credit_cards/create'
  get 'credit_cards/edit'
  post 'credit_cards/update'

  post 'stripe/webhook'

  get 'sales/new' => 'sales#new', as: :guest_checkout
  post 'sales/create' 
  get 'sales/show', as: :purchase_confirmation

  get 'products/show'
  get 'products/download' => 'products#download', as: :download
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'subscriptions/new' => 'subscriptions#new', as: :new_subscription
  post 'subscriptions/create' => 'subscriptions#create'
  
  get 'pricing' => 'welcome#pricing'
    

  root 'welcome#index'

end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
		<%= nav_link 'Home', root_path %>		  
		
		<% if user_signed_in? %>
		  <%= nav_link 'Logout', destroy_user_session_path, :delete %>
		  <%= nav_link 'My Account', edit_user_registration_path %>		  
		<% else %>
		  <%= nav_link 'Login', new_user_session_path %>
  		  <%= nav_link 'Register', new_user_registration_path %>
		<% end %>

	    <%= nav_link 'Products', products_show_path %>  		          
		<%= nav_link 'Pricing', pricing_path %>  		          
	    
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>