config/routes.rb
Rails.application.routes.draw do
  
  get 'credit_cards/new'
  post 'credit_cards/create'
  get 'credit_cards/edit'
  post 'credit_cards/update'

  post 'stripe/webhook'

  get 'sales/new' => 'sales#new', as: :guest_checkout
  post 'sales/create' 
  get 'sales/show', as: :purchase_confirmation

  get 'products/show'
  get 'products/download' => 'products#download', as: :download
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'subscriptions/new' => 'subscriptions#new', as: :new_subscription
  post 'subscriptions/create' => 'subscriptions#create'
  
  get 'pricing' => 'welcome#pricing'
    

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @orders = []
    
    if user_signed_in?
      @orders = current_user.orders if current_user.has_orders? 
    end
  end
  
  def pricing
  end
end

app/views/welcome/index.html.erb
<% if @orders %>
	Your Purchases <br/>
	<% @orders.each do |order|  %>
		<%= order[:product_name] %> : <%= order[:amount] %>
	<% end %>
	
<% else  %>
	This is the home page.
<% end  %>

app/views/welcome/pricing.html.erb
<fieldset>
	<legend>Pricing</legend>
	<div class='container'>
		<%= link_to 'Gold', new_subscription_path(:plan_name => 'gold') %> <br/>
		<%= link_to 'Silver', new_subscription_path(:plan_name => 'silver') %> <br/>
		<%= link_to 'Platinum', new_subscription_path(:plan_name => 'platinum') %> <br/>	
	</div>
	
</fieldset>