config/routes.rb
Rails.application.routes.draw do
  
  get 'credit_cards/new'
  post 'credit_cards/create'
  get 'credit_cards/edit'
  post 'credit_cards/update'

  post 'stripe/webhook'

  get 'sales/new' => 'sales#new', as: :guest_checkout
  post 'sales/create' 
  get 'sales/show', as: :purchase_confirmation

  get 'products/show'
  get 'products/download' => 'products#download', as: :download
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'subscriptions/new' => 'subscriptions#new', as: :new_subscription
  post 'subscriptions/create' => 'subscriptions#create'
  
  get 'pricing' => 'welcome#pricing'
    

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  def self.price_in_cents_for(product_id)
    product = Product.find(product_id)
    product.price_in_cents
  end
    
  def price_in_cents
    (price * 100).to_i
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def show
    @product = Product.first
  end
    
  def download
    @payment = Payment.find(params[:payment_id])
    @product = Product.find(params[:product_id])
    @credit_card = current_user.try(:credit_card)
    # Clear the session if they don't register after guest checkout
#    session[:guest_checkout] = nil
  end
end

app/views/products/download.html.erb
<fieldset>
	<legend>Confirmation</legend>
	
	Receipt Number : <%= @payment.receipt_number %>
	
	<p>You just bought <%= @product.name %> for <%= number_to_currency(@product.price) %>. 
			
	<% if @credit_card %>
		Your credit card ending in <%= @credit_card.last4digits %> has been charged for this purchase.
	<% end %>

	Download details about the book goes here.
</fieldset>

app/views/products/show.html.erb
<fieldset>
	<h1><%= @product.name %></h1>

	Price : <%= number_to_currency(@product.price) %>

	<%= link_to 'Buy Now', guest_checkout_path(id: @product), class: 'btn btn-primary' %>	
</fieldset>